frase = 'Curso em Vídeo Python'
print(frase[9])
print(frase[9:13])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(f"A frase '{frase}' têm {len(frase)} caracteres")
print(f"A letra 'o' aparece {frase.count('o')} vezes em '{frase}'")
print(f"Entre os caracteres 0 e 13, a letra 'o' aparece {frase.count('o',0,13)} vez")
print(f"Dentro da frase '{frase}', o conjunto de caracteres 'deo' começou na posição {frase.find('deo')}!")
print(f"Dentro da frase '{frase}', a string 'Android' não pode ser encontrado retornando o valor {frase.find('Android')}!")
print(f"Dentro da frase '{frase}', existe a palavra 'Curso'? {'Curso' in frase}")
print(f"Agora irei substituir 'Python' por 'Android' na frase '{frase}': '{frase.replace('Python','Android')}'")
print(f"Frase em maiúsculas: '{frase.upper()}'")
print(f"Frase em minúsculas: '{frase.lower()}'")